node {

  def webPath = '/home/docker/release-gurukahan'
  def dockerRegistry = 'dockerregistry.ecosmob.net:5000'

  stage('Checkout') {
    git branch: 'main', changelog: false, poll: false, url: 'https://github.com/Kunal918/node-app.git'
  }
stage('SonarQube analysis') {
      // requires SonarQube Scanner 2.8+
      //sh "npm install"
      def scannerHome = tool 'sonar-scanner';
      withSonarQubeEnv('sonar') {
        def sample = env.JOB_NAME.replaceAll('/', '.')
        def projectKey = sample.replaceAll('%2F', '.')
        sh "${scannerHome}/bin/sonar-scanner -D sonar.host.url='http://172.16.24.129:9000' -D sonar.projectKey=${projectKey}  -D sonar.sources=. -D sonar.exclusions=node_modules/**,Dockerfile,docker-compose.yml,default.conf"
        stash includes: ".scannerwork/report-task.txt", name: 'sonar'
      }
    }
}
